// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azklemxwhxaeomzgsboz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6a2xlbXh3aHhhZW9temdzYm96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzkzMzgsImV4cCI6MjA2NDU1NTMzOH0.wVCX-APVnLiQyC505MIDBloPOa5nZchOyeMYsL-n9Nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);